[project]
name = "blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "mkdocs-material>=9.6.14",
]

[dependency-groups]
dev = [
    "pre-commit>=3.0.0",
]
